### ISSUE TITLE
Remove the requirement to input your email address

### ISSUE THREAD

**Issue by RKBK** [chembrows/ChemBrows#1]
Hi!
I think your software looks very interesting, and I'd like to try it out. ChemBrows seems to cater to a very important need in science. However, smoke starts coming out of my ears when the first thing I see when I open a piece of FLOSS is a window prompting me to identify my academic status and submit my email address! And with no way of saying "No thanks". I think this needs to be fixed.

I'm sure news handling could be integrated in the client itself in some other way. Furthermore, if the user likes the software, I don't think you need to worry that they'll forget to update.

**Comment by JPFrancoia** [comment]
Hi ! Thanks for your interest in ChemBrows.
I understand your reluctance with giving your email address and your academic status. However, we thought about that:

- About the status: no need to worry, there is a "Obi Wan Kenobi" status. It is entirely up to the user to give us this metric.

- About the email: actually, even a fake email works. We do not send a verification email. We do not send any unnecessary email either. We need it in case something goes wrong and we can't fix it with an automated update. We want to be able to alert our users. We are not programmers, we are chemists, and we needed this assurance.

I hope I answered your questions
