### ISSUE TITLE
Clarify usage/purpose of "Liking" versus saving as "To read"

### ISSUE THREAD

**Issue by RKBK** [chembrows/ChemBrows#10]
In my current journal reading, I just have one action: saving for later. I save every article I want to look at in detail, and I never just "like" something, because that is not an action that has any practical consequences for me (if I like it, I should probably read it, and I never want to read it when I am in "going through new paper titles"-mode)

However, in chembrows, you can both like, and store for later. I understand that liking is what the ML algorithms uses to figure out what is hot to you. However, in my workflow, only storing stuff as to read (which also would be the same as liking, for the ML purpose) seems enough. What am I missing?

**Comment by JPFrancoia** [comment]
I think you workflow is too accurate at first glance. I usually send to the To Read list articles that **might** be interesting.

After a first look in the "All articles" mode, I switch to the To Read list and carefully read the abstracts. If an article deserves a like, I press the "Like" button. Liking an article is kind of an important action. It basically means "I want more articles like this one". Opening an article and not liking it means "I want less article like this one". Unread articles don't count, of course.

If I understand your question: you should click like for all the articles in your to read list.

**Comment by RKBK** [comment]
Now I understand your ideas for sending to read and liking better, and it seems smart. Not everything that seems interesting at first actually ends up being interesting when you look at it in more detail.
