### ISSUE TITLE
Some specific requests for further journals to be added

### ISSUE THREAD

**Issue by RKBK** [chembrows/ChemBrows#11]
Hi,
here is a list of journals that I follow presently and that I don't think are included in chembrows. My list perhaps indicates the need for a category system in the database, where users could choose to include or exclude e.g. physics journals (of which I still am interested in a few), chemical engineering journals, etc. 

The list is quite long. Is there any recommendation for how to contribute further journals? What needs to be included in the rss link? Can it be any rss link (i.e. just the one the publisher recommends) or is there more to it? If journals would be contributed through pull request, what is the required format of a new Journal entry?

The list:
- [ ] 2D Materials
- [ ] Acc Chem Res
- [ ] ACS Combin Sci
- [ ] Adsorption
- [ ] Adv Chem Eng
- [ ] Adv Inorg Chem
- [ ] Adv Mat
- [ ] Adv Synth Catal
- [ ] Advanced functional materials
- [ ] AIChe Journal
- [ ] Am J Phys
- [ ] Annu rev Anal Chem
- [ ] Annu rev cond mat
- [ ] Annu rev mater
- [ ] Annu rev phys chem
- [ ] Appl Catal A
- [ ] Appl Catal B
- [ ] Bioelectrochem
- [ ] Catal Commun
- [ ] Catal Sci Technol
- [ ] Catal Today
- [ ] Catalysts
- [ ] Chem Eng J
- [ ] Chem Eng Res
- [ ] Chem Eng Sci
- [ ] ChemElectroChem
- [ ] ChemPhysChem
- [ ] Chin J Catal
- [ ] Chin J Chem Eng
- [ ] Colloids and surfaces A
- [ ] Comp Chem Eng
- [ ] Computer Phys Commun
- [ ] Curr op chem eng
- [ ] ECS J Solid state sci technol
- [ ] ECS transactions
- [ ] Electrocatal
- [ ] Electrochem commun
- [ ] Electrochim Acta
- [ ] Ener Techn
- [ ] Fuel Cells Bull
- [ ] Ind Chem Lib
- [ ] Ind J Hydrogen En 
- [ ] Int J Quantum Chem
- [ ] J Catal
- [ ] J Chem Phys
- [ ] J Comput Chem
- [ ] J Electroanal Chem
- [ ] J Electrochem Soc
- [ ] J Engl Acad Purp
- [ ] J Indust Eng Chem
- [ ] J Molecular Catal A
- [ ] J Power Sources
- [ ] J Solid State Chem
- [ ] J Solid state electrochemistry
- [ ] Materials today
- [ ] Modelling and simulation in materials science and engineering
- [ ] Mol Simul
- [ ] Nano Today
- [ ] Nature Chem
- [ ] Nature Phys
- [ ] Phys chem chem phys
- [ ] Phys Rev Lett
- [ ] Phys Rev A
- [ ] Phys Rev B
- [ ] Prog Solid State Chem
- [ ] Prog Surf Sci
- [ ] Science Adv
- [ ] Surf Coat Technol
- [ ] Surf Sci
- [ ] Surf Sci Rep
- [ ] Thin Solid Films
- [ ] Wiley interdisciplinary reviews: computational molecular science
- [ ] Catalysis reviews (Taylor and francis, no RSS?)
- [ ] Advances in Physics (Taylor and francis)
- [ ] Critical reviews in solid state and materials science (Taylor and Francis)

**Comment by JPFrancoia** [comment]
Hi, sorry for the late answer.

This matter has been discussed in previous Pull Requests (PR):

- https://github.com/chembrows/ChemBrows/pull/2
- https://github.com/chembrows/ChemBrows/pull/4

You can consult my comments for the details. In short, here is what we plan for the future development of ChemBrows:

- The starting catalog already contains 120+ journals. They are (we think) the "principal" journals in chemistry. The user can easily choose among them

- If the user is not satisfied by the included selection of journal, he will soon have the possibility to add his own selection of journals (through commit e99b4c6b72f887574251ddd260bea42ac4af6f22). This commit brings a new feature: a wizard to easily add a new journal.

The new feature is ready and will be deployed with the next version of ChemBrows.

On a side note, I think some of the journals in your list are already present in the starting catalog.

**Comment by RKBK** [comment]
When will the new version of ChemBrows be released? Seeing as how the code for adding own journals seems to be implemented already, maybe a version with that very useful feature could be released soon-ish?

**Comment by JPFrancoia** [comment]
Hi, yes it is almost ready, but not totally. We haven't tested the code much, and I would like to implement the possibility to add any journal, from any publisher, with a "generic" template (this template would not perform as well as the specific ones, but could be used for any publisher, not just the 6-7 I mentioned before).
However, my PhD defence is approaching (less than 1 month), and I don't have much time to code. As soon as the defence is gone, I will have a lot of spare time to polish ChemBrows. I did not forget you !

**Comment by RKBK** [comment]
That sounds good! 

Best of luck for your PhD defence, @JPFrancoia !
