### ISSUE TITLE
Windows dependencies fail to install with Python 3

### ISSUE THREAD

**Issue by carlosperate** [chembrows/ChemBrows#14]
The PyUserInput depends on PyHooks on Windows, so trying to install with Python3 will fail as PyHooks is Python 2 only.
How do you install the unstable branch in Windows with Python 3.5?

**Comment by JPFrancoia** [comment]
Oh, sorry, I encountered this problem very recently and didn't correct it yet. Simply remove qtbot, pyuserinput and pyhooks from requirements.txt, they are necessary only to run the tests.

**Comment by carlosperate** [comment]
Looks like scipy cannot be pip installed either. How do you normally install dependencies on windows?

**Comment by JPFrancoia** [comment]
Well, ChemBrows is one of the most difficult software you can find to package. It uses PyQt5, scipy, numpy, scikit-learn, etc. If you manage to build it, you'll fear nothing.

As explained here: https://www.scipy.org/install.html

You need to install some wheels (2, actually). First install numpy, then scipy. You can find their wheels here: http://www.lfd.uci.edu/~gohlke/pythonlibs/

Then you just need to do:
```pip install my_wheel.whl```

**Comment by carlosperate** [comment]
Thanks for such a quick replied.
I've installed the scipy and numpy wheels from lfd.uci.edu/~gohlke/pythonlibs/ and they seem to work fine. Although I have not tested yet if the application runs correctly, as I am running the build in AppVeyor.

I was trying to replicate the steps you've mentioned in https://github.com/pyinstaller/pyinstaller/issues/1566#issuecomment-274826461 and now I am a stuck with trying to run the pyinstaller spec file.
You can see in here the output: https://ci.appveyor.com/project/carlosperate/chembrows/build/1.0.18
Trying to execute `pyinstaller deploy\gui_win.spec` it fails to find the gui.py script which should be in the cwd. Do you copy the gui_win.spec from the deploy folder into the root directory?

**Comment by carlosperate** [comment]
Yes, moving the gui_win.spec file to the root directory solved my previous issue.
Thanks for all the help!

**Comment by JPFrancoia** [comment]
Yes sorry, I normally move the corresponding spec file to the cwd. Glad you managed to find out the solution !
Did you manage to completely build the app, with all the missing dlls ?

**Comment by JPFrancoia** [comment]
Ok, I'll assume you managed to build the app. If not, I'll reopen the issue.

**Comment by carlosperate** [comment]
Hi @JPFrancoia, sorry I haven't been able to update you on this. I've encountered some issues with the output when built using PyInstaller, but I haven't had the chance to look into this since my last message.
Let's keep this one closed, and if I can find the time to go back to this and fix it (or figure out the problem) I can post a general update here.

**Comment by JPFrancoia** [comment]
Sounds great. Good luck !
