### ISSUE TITLE
suggestion: shorter version of "complete title"

### ISSUE THREAD

**Issue by nbehrnd** [chembrows/ChemBrows#6]
For publications by the American Chemical Society, I suggest to change the current policy of the complete titles -- like 

Organic Letters: Latest Articles (ACS Publications) 

into 

Organic Letters.  By similar token, instead of 

ScienceDirect Publication: Tetrahedron

for example, in the section of journals provided by Elsevier, to (re)turn to

Tetrahedron

as the title used (even if abbreviated) in citations, too.  As a benefit in maintaining the software (i.e. ChemBrows), entries in the publisher.ini files are easier to read / to organize, for example in alphabetical order of the journals in question.

**Comment by JPFrancoia** [comment]
Hi,

That's actually impossible. The .ini files in the journal folder are not meant to be read by the users. They are meant to check if the RSS pages downloaded by ChemBrows while parsing new articles are correct.

Exemple: let's take 'Proteins', from Wiley

ChemBrows will download the RSS page at http://onlinelibrary.wiley.com/rss/journal/10.1002/(ISSN)1097-0134.
In the ini file, the title will be: Proteins: Structure, Function, and Bioinformatics

If the title in the ini file matches the one from the RSS page, then ChemBrows will start to analyze it.
It's a mandatory verification process.
